# Generated by Django 3.2.8 on 2021-11-07 16:37

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='userEmail',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='userName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='user',
            name='userImage',
            field=models.ImageField(blank=True, default='default/default_user.png', null=True, upload_to=api.models.get_file_path_user),
        ),
        migrations.AddField(
            model_name='user',
            name='userPassword',
            field=models.CharField(default='NULL', max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
