# Generated by Django 3.2.8 on 2021-11-07 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211108_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userPassword',
        ),
    ]
