# Generated by Django 3.2.8 on 2021-11-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_username_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userPhone',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
