# Generated by Django 3.2.8 on 2021-11-07 17:27

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_userphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canteen',
            fields=[
                ('canteenID', models.BigAutoField(primary_key=True, serialize=False)),
                ('canteenName', models.CharField(max_length=30, unique=True)),
                ('canteenAddress', models.CharField(max_length=60)),
                ('canteenImage', models.ImageField(blank=True, default='default_canteen.jpg', null=True, upload_to=api.models.get_file_path_canteen)),
                ('canteenIntro', models.CharField(blank=True, max_length=300)),
                ('canteenType', models.IntegerField()),
                ('canteenOperationTime', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
