# Generated by Django 3.2.8 on 2021-11-07 17:35

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_canteen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stall',
            fields=[
                ('stallID', models.BigAutoField(primary_key=True, serialize=False)),
                ('stallName', models.CharField(max_length=30, unique=True)),
                ('stallAddress', models.CharField(max_length=60)),
                ('stallImage', models.ImageField(blank=True, default='default_canteen.jpg', null=True, upload_to=api.models.get_file_path_canteen)),
                ('stallDescribe', models.CharField(blank=True, max_length=300)),
                ('stallRate', models.FloatField(blank=True)),
                ('stallRateNum', models.IntegerField(blank=True)),
                ('canteenID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.canteen')),
            ],
        ),
    ]
