# Generated by Django 3.2.8 on 2021-11-08 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211108_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stallID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stall')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stallRate', models.FloatField()),
                ('stallID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stall')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LikeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.review')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LikeDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dish')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DishReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dish')),
                ('reviewID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.review')),
            ],
        ),
    ]
