# Generated by Django 3.2.8 on 2021-11-08 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_dishreview_likedish_likereview_ratings_userstall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='userName',
        ),
    ]
