# Generated by Django 3.2.8 on 2021-11-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_username_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userEmail',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
