# Generated by Django 3.2.8 on 2021-11-08 13:03

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_user_useremail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reviewImages',
        ),
        migrations.RemoveField(
            model_name='stall',
            name='stallImage',
        ),
        migrations.CreateModel(
            name='StallImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stallImage', models.ImageField(blank=True, default='default/default_stall.jpg', null=True, upload_to=api.models.get_file_path_stall)),
                ('stallID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stall')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewImages', models.ImageField(blank=True, null=True, upload_to=api.models.get_file_path_review)),
                ('reviewID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.review')),
            ],
        ),
    ]
