# Generated by Django 3.2.8 on 2021-11-09 16:51

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20211108_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('first_login', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('userImage', models.ImageField(blank=True, default='default/default_user.png', null=True, upload_to=api.models.get_file_path_user)),
                ('userEmail', models.EmailField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='userEmail',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userImage',
        ),
        migrations.AlterField(
            model_name='stallimage',
            name='stallImage',
            field=models.ImageField(blank=True, default='default/default_stall.png', null=True, upload_to=api.models.get_file_path_stall),
        ),
    ]
