# Generated by Django 3.2.8 on 2021-11-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20211110_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userPhone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
