# Generated by Django 3.2.8 on 2021-11-17 11:35

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_user_userphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticeCreateTime', models.DateTimeField(auto_created=True)),
                ('noticeImage', models.ImageField(blank=True, null=True, upload_to=api.models.get_file_path_notice)),
                ('noticeType', models.CharField(choices=[('ADVERTISEMENT', 'ADVERTISEMENT'), ('NOTICE', 'NOTICE')], max_length=20)),
                ('noticeName', models.CharField(max_length=50)),
            ],
        ),
    ]
