# Generated by Django 3.2.8 on 2021-11-17 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplyByStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replyContent', models.CharField(blank=True, max_length=500)),
                ('replyDateTime', models.DateTimeField(auto_now=True)),
                ('parent_reviewID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.review')),
                ('stallID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.stall')),
            ],
        ),
    ]
