# Generated by Django 3.2.8 on 2021-11-23 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20211118_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='stallID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.stall'),
        ),
        migrations.DeleteModel(
            name='UserStall',
        ),
    ]
