# Generated by Django 3.2.8 on 2021-11-24 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20211124_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staffName',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
