# Generated by Django 3.2.8 on 2021-11-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_staff_staffname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='noticeName',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='noticeType',
        ),
        migrations.AddField(
            model_name='notice',
            name='noticeTitle',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AddField(
            model_name='notice',
            name='noticeWords',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
