# Generated by Django 3.2.8 on 2021-11-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20211124_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stall',
            name='stallAddress',
        ),
        migrations.AddField(
            model_name='stall',
            name='stallFloor',
            field=models.IntegerField(null=True),
        ),
    ]
