# Generated by Django 3.2.8 on 2021-11-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall',
            name='stallRateNum',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
