# Generated by Django 3.2.8 on 2021-11-24 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_delete_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='noticeCreateTime',
        ),
    ]
