# Generated by Django 3.2.8 on 2021-11-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_notice_noticecreatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
