# Generated by Django 3.2.8 on 2021-11-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_stall_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staffID',
            field=models.IntegerField(default=0),
        ),
    ]
