# Generated by Django 3.2.8 on 2021-11-24 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_staff_staffid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('first_login', models.BooleanField(default=True)),
                ('adminName', models.CharField(default=None, max_length=10)),
                ('adminID', models.IntegerField(default=0)),
            ],
        ),
    ]
