# Generated by Django 3.2.8 on 2021-11-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_notice_noticeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall',
            name='stallName',
            field=models.CharField(max_length=30),
        ),
    ]
