# Generated by Django 3.2.8 on 2021-11-26 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_stall_stallname'),
    ]

    operations = [
        migrations.AddField(
            model_name='canteen',
            name='canteenPhone',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
