# Generated by Django 3.2.8 on 2021-11-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_canteen_canteenfloor'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
