# Generated by Django 3.2.8 on 2021-12-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_stall_stalloperationtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall',
            name='stallOperationtime',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
