# Generated by Django 3.2.8 on 2021-12-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_dish_dishname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='dishAvailableTime',
            field=models.CharField(default='1234', max_length=15),
        ),
    ]
