# Generated by Django 3.2.8 on 2021-12-14 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_dish_dishavailabletime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='dishImage',
        ),
    ]
