# Generated by Django 3.2.8 on 2021-12-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_remove_dish_dishimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stall',
            name='stallRate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
